on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  snowflake-to-slack:
    runs-on: ubuntu-latest
    name: snowflake to slack
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.3
      - name: Slack message 1
        uses: offbi/snowflake-to-slack@1.0.0
        with:
          user: ${{ secrets.USER }}
          password: "${{ secrets.PASSWORD }}"
          account: "qz86222"
          warehouse: "BI_TEAM_WH"
          database: "DBT_DEV"
          role: "BI_DATA_ENGINEER"
          slack-token: "xoxb-10049520935-1494791191025-cmnSU5fK9sF0Hq7lmQEN9tVA"
          sql: "SELECT * FROM record_breaker"
